site_name: Growth and Common Platform
site_url: https://example.com/
repo_url: https://github.com/kritika3/Mkdocs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Deploy Documentation
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Deploy
        run: |
          git pull
          mkdocs gh-deploy